### PR TITLE
Added kw-np command arguments.

### PR DESCRIPTION
**Pull request by matglas**
I added arguments to the kw-np command so that I am able to test my skeleton quickly. Now I don't have to type the input every time but just run my bash script to create a new test setup.

### CODE REVIEW

**Comment by matglas** [comment]
@rolfvandekrol would you consider merging this in?

**Comment by FransvanderMeer** [comment]
+1

**Comment by rolfvandekrol** [comment]
Looks good, in general. I added a few comments to the code. If those points are addressed, I'll merge this in.

**Comment by matglas** [comment]
I changed the command based on your feedback. No problem.

**Comment by rolfvandekrol** [comment]
Looks good to me! :+1: Let's merge this in.

**Pull request merged**
