### PR TITLE
Relative symlinks

### PR DESCRIPTION
**Pull request by jerbob92**
Creates relative symlinks with support for the old method with a kraftwagenrc.php setting.

### CODE REVIEW

**Comment by matglas** [comment]
+1
I want to use kraftwagen inside docker and I really need this feature.

**Comment by bighappyface** [comment]
+1

I applied this PR patch to the latest ran through a fresh setup and build that is shared between my local environment and a vagrant machine. Works perfectly :beers:

**Comment by matglas** [comment]
I did the same here after seeing it. I ran it inside a Docker setup and it works perfectly.

**Comment by jerbob92** [comment]
@rolfvandekrol 
What do you think?
I wasn't sure the ```getcwd``` and ```chdir``` were needed. I added them to be sure the symlinks were created from the proper folder.

**Comment by bighappyface** [comment]
@rolfvandekrol any movement on this? I am ready when you are :smile_cat:

**Comment by rolfvandekrol** [comment]
Sorry for the delay. Merged this in, after some cleaning up of the code. 

I changed some minor code style related stuff in the `kraftwagen_get_relative_path` function. It used camelCase, while Drupal (and Drush and Kraftwagen) uses underscore. I also prefer early returns (which is used everywhere in Kraftwagen, afaik, and if not: pull requests are appreciated).

The second thing I changed is that I moved the symlink logic to a separate function that is used by both kraftwagen commands.

Thanks for your contribution!

**Comment by bighappyface** [comment]
@rolfvandekrol @jerbob92 thanks guys!

**Pull request closed without merging**
