### PR TITLE
Hotfix/kw amd error

### PR DESCRIPTION
**Pull request by matglas**
This fixes undisplayed error messages where relevant information is provided to debug a kw-amd with unmet dependencies.

### CODE REVIEW

**Comment by wietzehiha** [comment]
You fix my build, thank you!

**Comment by rolfvandekrol** [comment]
@matglas the change in the input parameters is clear, but why separating the `return` and the `drush_set_error` into two lines? `drush_set_error` shoud always return `FALSE`.

**Comment by matglas** [comment]
Ill revert that. Does that function return false?
Op wo 13 dec. 2017 om 11:57 schreef Rolf van de Krol <
notifications@github.com>

**Comment by rolfvandekrol** [comment]
@matglas it always returns false. http://api.drush.org/api/drush/includes%21drush.inc/function/drush_set_error/8.0.x

**Pull request closed without merging**
