### PR TITLE
41 activate build

### PR DESCRIPTION
**Pull request by matglas**
Fixing #41 
Only the support for previous build is not there.

### CODE REVIEW

**Comment by bighappyface** [comment]
@matglas the build selection works great!

When passing the build argument, I used the build number instead of the full path to the build and get the following:

```bash
$ drush kw-activate-build 20150327-122556
symlink(): File exists kraftwagen.fileutils.inc:112
Symlinked '20150327-122556' to '/Users/davi4797/containers/workspace/www/build'.

$ bin/drush kw-activate-build 20150327-122556
Build at 20150327-122556 is already activated.

$ ll ..
total 1017560
drwxr-xr-x  14 bighappyface  bighappyface        476 Mar 27 12:30 .
drwxrwxrwx  59 bighappyface  bighappyface       2006 Mar  5 00:05 ..
drwxrwxr-x   4 bighappyface  bighappyface        136 Mar 27 12:27 builds
drwxrwxr-x   6 bighappyface  bighappyface        204 Mar 24 12:11 cnf
drwxr-xr-x  35 bighappyface  bighappyface       1190 Mar 27 12:25 src
```

The selection leads me to think that I can simply pass the build folder name and not the full path as the optional argument. This is mostly a UX concern, and I recommend the build argument is just the directory name for this context. That should address the UX issue, as well as the warning and missing symlink issue.

**Comment by matglas** [comment]
@bighappyface this should fix it. You can now use the build dir name or the full path. Or leave it empty and get the list.

**Comment by bighappyface** [comment]
@matglas working like a charm :beers: 

+1

**Comment by handrus** [comment]
+1!

**Comment by bighappyface** [comment]
@rolfvandekrol may we move forward with this?

**Comment by rolfvandekrol** [comment]
Hi @matglas 

Sorry for the late reaction. Been very busy lately. 

The concept looks good. The code looks a lot like `drush_choice` (https://github.com/drush-ops/drush/blob/master/includes/drush.inc#L443-L508). Is it possible to use `drush_choice` instead of having our own implementation of it?

Rolf

**Comment by matglas** [comment]
Not working with Drupal a lot anymore. And this ticket is so old. Closing it now.

**Pull request closed without merging**
